version: '3.8'

services:
  mysqlalsea:
    image: mysql:latest
    container_name: mysqlalsea
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: alseadb
      MYSQL_USER: miusuario
      MYSQL_PASSWORD: miuserpassword
    ports:
      - "3308:3306"
    networks:
      - local_alsea

  alseabackend:
    image: alsea_backend:latest
    depends_on:
      - mysqlalsea
    ports:
      - "8080:8080"
    environment:
      HOST_DB: mysqlalsea
      PORT_DB: 3306
      NAME_DB: alseadb
      USER_DB: miusuario
      PW_DB: miuserpassword
      PORT_APP: 8080
      DDL_AUTO: create-drop
    networks:
      - local_alsea

networks:
  local_alsea:
    driver: bridge
