INSERT INTO paises (codigo, nombre, utc) VALUES ('CL', 'Chile', 'UTC-04');
INSERT INTO paises (codigo, nombre, utc) VALUES ('COL', 'Colombia', 'UTC-05');
INSERT INTO paises (codigo, nombre, utc) VALUES ('MX', 'México', 'UTC-06');
INSERT INTO paises (codigo, nombre, utc) VALUES ('AR', 'Argentina', 'UTC-03');
INSERT INTO paises (codigo, nombre, utc) VALUES ('BR', 'Brasil', 'UTC-03');
INSERT INTO paises (codigo, nombre, utc) VALUES ('PE', 'Perú', 'UTC-05');
INSERT INTO paises (codigo, nombre, utc) VALUES ('VE', 'Venezuela', 'UTC-04');
INSERT INTO paises (codigo, nombre, utc) VALUES ('EC', 'Ecuador', 'UTC-05');
INSERT INTO paises (codigo, nombre, utc) VALUES ('BO', 'Bolivia', 'UTC-04');
INSERT INTO paises (codigo, nombre, utc) VALUES ('UY', 'Uruguay', 'UTC-03');
INSERT INTO paises (codigo, nombre, utc) VALUES ('PY', 'Paraguay', 'UTC-04');
INSERT INTO paises (codigo, nombre, utc) VALUES ('CR', 'Costa Rica', 'UTC-06');
INSERT INTO paises (codigo, nombre, utc) VALUES ('GT', 'Guatemala', 'UTC-06');
INSERT INTO paises (codigo, nombre, utc) VALUES ('SV', 'El Salvador', 'UTC-06');
INSERT INTO paises (codigo, nombre, utc) VALUES ('HN', 'Honduras', 'UTC-06');
INSERT INTO paises (codigo, nombre, utc) VALUES ('NI', 'Nicaragua', 'UTC-06');
INSERT INTO paises (codigo, nombre, utc) VALUES ('PA', 'Panamá', 'UTC-05');
INSERT INTO paises (codigo, nombre, utc) VALUES ('DO', 'República Dominicana', 'UTC-04');
INSERT INTO paises (codigo, nombre, utc) VALUES ('CU', 'Cuba', 'UTC-05');
INSERT INTO paises (codigo, nombre, utc) VALUES ('PR', 'Puerto Rico', 'UTC-04');